### ISSUE TITLE
Incompatibility with Sirius 7.x

### ISSUE THREAD

**Issue by TizGecko** [altran-mde/xtext-sirius-integration#6]
That's a breaking change in Sirius 7.x that makes impossible to use the DirectEditLabel component of this plugin.

I report a runtime ClassCastException affecting the DirectEditLabel for an expression subjected to an Xtext grammar. The error is due to the renaming of the SiriusPlugin class (that in version 7.x changed its belonging package from **org.eclipse.sirius.viewpoint.SiriusPlugin** to **org.eclipse.sirius.tools.api.SiriusPlugin**). 

That's the comment on the official [Release Notes](https://eclipse.dev/sirius/doc/Release_Notes.html)

> MODIFIED org.eclipse.sirius.viewpoint.SiriusPlugin has been renamed to org.eclipse.sirius.tools.api.SiriusPlugin

This is my exception trace:
```
java.lang.NoClassDefFoundError: org/eclipse/sirius/viewpoint/SiriusPlugin
	at com.altran.general.integration.xtextsirius.runtime.editpart.ui.XtextSiriusDirectEditPolicy.addChildTasks(XtextSiriusDirectEditPolicy.java:106)
	at com.altran.general.integration.xtextsirius.runtime.editpart.ui.XtextSiriusDirectEditPolicy.getDirectEditCommand(XtextSiriusDirectEditPolicy.java:83)
	at org.eclipse.gef.editpolicies.DirectEditPolicy.getCommand(DirectEditPolicy.java:58)
	at org.eclipse.gef.editparts.AbstractEditPart.getCommand(AbstractEditPart.java:485)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart.access$1(GraphicalEditPart.java:1)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart$1.run(GraphicalEditPart.java:483)
	at org.eclipse.emf.transaction.impl.TransactionalEditingDomainImpl.runExclusive(TransactionalEditingDomainImpl.java:328)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart.getCommand(GraphicalEditPart.java:478)
	at org.yakindu.base.xtext.utils.gmf.directedit.DirectEditManagerEx.commit(DirectEditManagerEx.java:146)
	at org.yakindu.base.xtext.utils.gmf.directedit.XtextDirectEditManager.commit(XtextDirectEditManager.java:375)
	at org.yakindu.base.xtext.utils.gmf.directedit.DirectEditManagerEx$3.applyEditorValue(DirectEditManagerEx.java:293)
	at org.eclipse.jface.viewers.CellEditor$1.run(CellEditor.java:335)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.CellEditor.fireApplyEditorValue(CellEditor.java:332)
	at org.eclipse.jface.viewers.CellEditor.focusLost(CellEditor.java:714)
	at org.yakindu.base.xtext.utils.jface.viewers.XtextStyledTextCellEditor.focusLost(XtextStyledTextCellEditor.java:213)
	at org.yakindu.base.xtext.utils.jface.viewers.XtextStyledTextCellEditor$3.handleEvent(XtextStyledTextCellEditor.java:116)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4441)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6101)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5795)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4441)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1549)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Canvas.sendKeyEvent(Canvas.java:522)
	at org.eclipse.swt.widgets.Control.doCommandBySelector(Control.java:1085)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6246)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents(NSResponder.java:59)
	at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:606)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6078)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2150)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2487)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6198)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5442)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5585)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3834)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1435)
Caused by: java.lang.ClassNotFoundException: org.eclipse.sirius.viewpoint.SiriusPlugin cannot be found by com.altran.general.integration.xtextsirius.runtime.editpart.ui_1.0.0.20210607-0849
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 73 more
```

I hope this could be fixed soon.

**Comment by arcanefoam** [comment]
We have forked this  project and updated it to work with recent versions of Eclipse, Xtext and Sirius (7.1+): 
https://github.com/t-chiang/xtext-sirius-integration

Since this repo seems no longer maintained, hopefully you can use our fixes.
